server:
  port: 9000

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        CorsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: stockMicoroservice
          uri: http://localhost:8081/
          predicates:
            - Path= /authenticate
        - id: stockMicoroservice
          uri: https://localhost:8443/
          predicates:
            - Path= /api/v1.0/market/company/register

        - id: stockMicoroservice
          uri: http://localhost:8081/
          predicates:
            - Path= /api/v1.0/market/company/info/**

        - id: stockMicoroservice
          uri: http://localhost:8081/
          predicates:
            - Path= /api/v1.0/market/company/getall/**

        - id: stockMicoroservice
          uri: https://localhost:8443/
          predicates:
            - Path= /api/v1.0/market/company/delete/**

        - id: stockMicoroservice
          uri: http://localhost:8081/
          predicates:
            - Path= /v2/api-docs